# Generated by Math Visualization. Render with ManimGL 1.7.2, for example:
#     python -m manimlib this_file.py MatrixTransformation -w
#
# This file is a template: Math Visualization replaces __SPEC_JSON__ with the
# scene specification (a JSON string literal) before running it. It is never
# imported by the application itself.
#
# The animation is Manim's own linear transformation: every point moves on a
# straight line from p to A·p with the chosen rate function, the same
# interpolation the live preview uses.

import json

from manimlib import *  # noqa: F401,F403 (ManimGL's documented usage)

SPEC = json.loads(__SPEC_JSON__)  # noqa: F821 (replaced on export)

RATE_FUNCTIONS = {"smooth": smooth, "linear": linear}


def point(xy, z=0.0):
    return np.array([xy[0], xy[1], z], dtype=float)


def plane(extent, step, style):
    return NumberPlane(
        x_range=(-extent, extent, step),
        y_range=(-extent, extent, step),
        background_line_style=style,
        faded_line_ratio=0,
    )


class MatrixTransformation(Scene):
    def construct(self):
        spec = SPEC
        colors = spec["colors"]
        matrix = np.array(spec["matrix"], dtype=float)
        grid = spec["grid"]
        self.set_up_frame(spec)

        # The untransformed plane stays behind as a faint reference.
        background = plane(grid["background_extent"], grid["step"],
                           dict(stroke_color=GREY_C, stroke_width=1, stroke_opacity=0.35))
        background.axes.set_stroke(GREY_B, 1.5, 0.6)
        self.add(background)
        if spec["mode"] == "3d":
            reach = grid["background_extent"]
            self.add(Line(point((0, 0), -reach), point((0, 0), reach)).set_stroke(GREY_B, 1.5, 0.6))

        # Mobjects whose every point is mapped by A.
        mapped = VGroup()
        if spec["show_grid"]:
            moving = plane(grid["extent"], grid["step"],
                           dict(stroke_color=colors["grid"], stroke_width=2, stroke_opacity=1))
            moving.axes.set_stroke(WHITE, 2, 1)
            mapped.add(moving)
        if spec["show_unit_square"]:
            square = Polygon(point((0, 0)), point((1, 0)), point((1, 1)), point((0, 1)))
            square.set_fill(colors["unit_square"], 0.3).set_stroke(colors["unit_square"], 1)
            mapped.add(square)

        # Arrows are redrawn at A·v rather than mapped point by point, so their
        # tips keep their shape; the tip itself still moves from v to A·v.
        arrows = []
        if spec["show_basis"]:
            arrows.append((point((1, 0)), colors["i_hat"], None))
            arrows.append((point((0, 1)), colors["j_hat"], None))
        for vector in spec["vectors"]:
            arrows.append((point(vector["components"]), vector["color"], vector["name"]))

        animations = [ApplyMatrix(matrix, mapped)] if len(mapped) else []
        for start, color, name in arrows:
            end = np.append(matrix @ start[:2], 0.0)
            if np.linalg.norm(start) < 1e-9:
                self.add(Dot(ORIGIN, radius=0.06, fill_color=color))
                continue
            arrow = Vector(start, fill_color=color)
            target = Vector(end, fill_color=color) if np.linalg.norm(end) > 1e-9 else arrow.copy().scale(0, about_point=ORIGIN)
            self.add(arrow)
            animations.append(Transform(arrow, target))
            if name:
                label = Text(name, font_size=30, slant=ITALIC).set_color(color)
                label.add_updater(lambda m, a=arrow: m.next_to(a.get_end(), UR, buff=0.08))
                self.add(label)

        self.add(mapped)
        self.bring_to_back(mapped)
        self.bring_to_back(background)
        self.wait(spec["hold_before"])
        if animations:
            self.play(*animations, run_time=spec["duration"], rate_func=RATE_FUNCTIONS[spec["rate_function"]])
        self.wait(spec["hold_after"])

    def set_up_frame(self, spec):
        frame = self.frame
        if spec["mode"] == "3d":
            camera = spec["camera_3d"]
            frame.reorient(camera["theta"], camera["phi"])
            frame.set_height(camera["height"])
            frame.move_to(np.array(camera["center"], dtype=float))
        else:
            frame.set_height(spec["frame_2d"]["height"])
            frame.move_to(point(spec["frame_2d"]["center"]))
